### ISSUE TITLE
v8.0.0 healthz error - container remains unhealthy

### ISSUE THREAD

**Issue by mcoakley** [muhlba91/external-dns-provider-adguard#206]
I've configured external-dns using the official Helm chart and the integration is working as expected but the external-dns-provider-adgaurd container remains unhealthy with the following event being reported:

```
Warning  Unhealthy  3m51s (x3270 over 9h)  kubelet  Liveness probe errored: strconv.Atoi: parsing "healthz": invalid syntax 
```

Here are my Helm values that I used (redacted):

```yaml
---
resources:
  limits:
    cpu: 150m
    ephemeral-storage: 2Gi
    memory: 192Mi
  requests:
    cpu: 100m
    ephemeral-storage: 50Mi
    memory: 128Mi

txtOwnerId: example.com

domainFilters:
  - example.com

extraArgs:
  - --webhook-provider-url=http://localhost:8888

provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/muhlba91/external-dns-provider-adguard
      tag: v8.0.0
      pullPolicy: IfNotPresent
    env:
      - name: LOG_LEVEL
        value: debug
      - name: ADGUARD_URL
        valueFrom:
          secretKeyRef:
            key: url
            name: adguard-configuration
      - name: ADGUARD_USER
        valueFrom:
          secretKeyRef:
            key: user
            name: adguard-configuration
      - name: ADGUARD_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: adguard-configuration
      - name: DRY_RUN
        value: "false"
    resources:
      limits:
        cpu: 150m
        ephemeral-storage: 2Gi
        memory: 192Mi
      requests:
        cpu: 100m
        ephemeral-storage: 50Mi
        memory: 128Mi
    livenessProbe:
      httpGet:
        path: /healthz
        port: healthz
      initialDelaySeconds: 10
      timeoutSeconds: 5
    ports:
      - containerPort: 8888
        name: http
      - containerPort: 8080
        name: healthz
    readinessProbe:
      httpGet:
        path: /healthz
        port: healthz
      initialDelaySeconds: 10
      timeoutSeconds: 5
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 20000
      runAsNonRoot: true
      runAsUser: 20000
```

Edit 1: Adding more information

After reading more code I can see that when a health request comes in and logging is set to debug I should see "requesting health" in the logs. I do not. 

Here is the start of the logs to show the startup of the container:

```json
{"level":"info","msg":"creating adguard provider with no kind of domain filters","time":"2025-01-31T12:41:30Z"}

external-dns-provider-adguard
version: v8.0.0 (7e9828a)

{"level":"debug","msg":"using adguard at http://adguard","time":"2025-01-31T12:41:30Z"}
{"level":"debug","msg":"making GET request to /status","time":"2025-01-31T12:41:30Z"}
{"level":"debug","msg":"response code from GET request to status: 200","time":"2025-01-31T12:41:31Z"}
{"level":"debug","msg":"retrieved status: {Version:v0.107.55 Running:true}","time":"2025-01-31T12:41:31Z"}
{"level":"info","msg":"starting server on addr: 'localhost:8888' ","time":"2025-01-31T12:41:31Z"}
{"level":"info","msg":"starting healthz on addr: '0.0.0.0:8080' ","time":"2025-01-31T12:41:31Z"}
```

Edit 2: Adding additional logs (to show it is working as expected)

After the above startup logs, the rest of the logs are filled with this sequence:

```json
{"level":"debug","msg":"requesting records","requestMethod":"GET","requestPath":"/records","time":"2025-01-31T12:41:31Z"}
{"level":"debug","msg":"making GET request to /filtering/status","time":"2025-01-31T12:41:31Z"}
{"level":"debug","msg":"response code from GET request to filtering/status: 200","time":"2025-01-31T12:41:32Z"}
{"level":"debug","msg":"retrieved filtering rules: {UserRules:[<3 rules redacted>]}","time":"2025-01-31T12:41:32Z"}
{"level":"debug","msg":"found rule <found rule redacted>","time":"2025-01-31T12:41:32Z"}
{"level":"debug","msg":"found rule <found rule redacted>","time":"2025-01-31T12:41:32Z"}
{"level":"debug","msg":"found rule <found rule redacted>","time":"2025-01-31T12:41:32Z"}
{"level":"debug","msg":"returning records count: 3","requestMethod":"GET","requestPath":"/records","time":"2025-01-31T12:41:32Z"}
{"level":"debug","msg":"requesting adjust endpoints count: 1","time":"2025-01-31T12:41:32Z"}
{"level":"debug","msg":"return adjust endpoints response, resultEndpointCount: 1","time":"2025-01-31T12:41:32Z"}
```

Edit 3: BusyBox testing

I added a BusyBox container to the external-dns Deployment to test the `healthz` endpoint. Here are the results:

```bash
~ $ wget http://localhost:8080/healthz
Connecting to localhost:8080 (127.0.0.1:8080)
wget: can't open 'healthz': Permission denied
~ $ wget http://localhost:8080/anything-else
Connecting to localhost:8080 (127.0.0.1:8080)
wget: server returned error: HTTP/1.1 404 Not Found
```
> NOTE: I accessed a non-existent URL just to show it was actually connecting to the server. Still no logs that show the connection thought. (Which makes sense since the proper endpoint responds with a Permission denied error).
